#!/usr/bin/env python3
"""
Interactive guide to fill in FLNet_client/self_signed_certs/san.cnf.
Run this before create_self_signed_certs.sh.
"""
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
SAN_CNF_PATH = BASE_DIR / 'FLNet_client' / 'self_signed_certs' / 'san.cnf'


def ask(prompt: str, example: str = "", required: bool = True) -> str:
    hint = f" (e.g. {example})" if example else ""
    while True:
        value = input(f"{prompt}{hint}: ").strip()
        if value:
            return value
        if not required:
            return ""
        print("  This field is required.")


def ask_list(prompt: str, example: str = "") -> list[str]:
    hint = f" (e.g. {example})" if example else ""
    print(f"{prompt}{hint}")
    print("  Enter one per line. Leave blank and press Enter when done.")
    items = []
    while True:
        val = input(f"  Entry {len(items) + 1}: ").strip()
        if not val:
            break
        items.append(val)
    return items


def main():
    print("=" * 60)
    print("  FLNet Client — Self-Signed Certificate Configuration")
    print("=" * 60)
    print(f"\nThis script fills in {SAN_CNF_PATH}")
    print("The resulting san.cnf is used by create_self_signed_certs.sh\n")

    if not SAN_CNF_PATH.exists():
        print(f"ERROR: {SAN_CNF_PATH} not found.")
        sys.exit(1)

    print("--- Distinguished Name (who the certificate is issued to) ---\n")
    country   = ask("Country code (2 letters)", "DE")
    if len(country) != 2 or not country.isalpha():
        print("WARNING: Country code should be exactly 2 letters (e.g. DE, US, AT).")
    state     = ask("State or province", "Bavaria")
    city      = ask("City", "Munich")
    org       = ask("Organization name", "My Hospital GmbH")
    unit      = ask("Organizational unit", "IT Department")
    cn        = ask("Common name (primary hostname or IP)", "myserver.example.com")

    print("\n--- Subject Alternative Names (SANs) ---\n")
    print("SANs tell browsers which hostnames/IPs this certificate is valid for.")
    print("Modern browsers require SANs — the Common Name above alone is not enough.\n")

    dns_names = ask_list("DNS hostnames", "myserver.example.com")
    ip_addrs  = ask_list("IP addresses (leave blank to skip)", "192.168.1.100")

    if not dns_names and not ip_addrs:
        print("\nERROR: At least one DNS hostname or IP address is required.")
        sys.exit(1)

    print("\n--- Certificate validity ---\n")
    days_input = ask("Validity in days", "365", required=False)
    days = int(days_input) if days_input.isdigit() else 365
    print(f"  Certificate will be valid for {days} days.")

    # Build alt_names block
    alt_lines = []
    for i, name in enumerate(dns_names, start=1):
        alt_lines.append(f"DNS.{i} = {name}")
    for i, ip in enumerate(ip_addrs, start=1):
        alt_lines.append(f"IP.{i}  = {ip}")
    alt_block = "\n".join(alt_lines)

    cnf_content = f"""\
# OpenSSL configuration for a self-signed certificate with Subject Alternative Names.
# Generated by fill_san_cnf.py — edit manually if needed.
# Re-run create_self_signed_certs.sh after any changes.

[req]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn
x509_extensions    = v3_ca

[dn]
C  = {country.upper()}
ST = {state}
L  = {city}
O  = {org}
OU = {unit}
CN = {cn}

[v3_ca]
basicConstraints   = CA:FALSE
keyUsage           = digitalSignature, keyEncipherment
extendedKeyUsage   = serverAuth
subjectAltName     = @alt_names

[alt_names]
{alt_block}
"""

    SAN_CNF_PATH.write_text(cnf_content)
    print(f"\nSAN config written to:\n  {SAN_CNF_PATH}")
    print(f"\nCertificate validity set to {days} days.")
    print("  (The validity is passed directly to create_self_signed_certs.sh via -days flag.)")
    print(f"\nNext step: run  ./create_self_signed_certs.sh {days}")
    print("  or just:  ./create_self_signed_certs.sh  (defaults to 365 days)")


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nAborted.")
        sys.exit(1)
